// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/dlukt/pdns-manager/ent/schema"
	"github.com/dlukt/pdns-manager/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[4].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
}
